// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFd-yM2ItbElezYUPoXmIC2dcWc6l293M',
    appId: '1:30693532203:web:767dfcf47980cd7d43006e',
    messagingSenderId: '30693532203',
    projectId: 'nectar-bbe2b',
    authDomain: 'nectar-bbe2b.firebaseapp.com',
    storageBucket: 'nectar-bbe2b.appspot.com',
    measurementId: 'G-DSQX44NQJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZjBbMVvwoZNx3Cx5fkcm7GpsJmnVmvLQ',
    appId: '1:30693532203:android:267a212ce01d8be843006e',
    messagingSenderId: '30693532203',
    projectId: 'nectar-bbe2b',
    storageBucket: 'nectar-bbe2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHONORJcW2h8CQERfcMYC9fvZErggJQgo',
    appId: '1:30693532203:ios:be5d4f9df181606443006e',
    messagingSenderId: '30693532203',
    projectId: 'nectar-bbe2b',
    storageBucket: 'nectar-bbe2b.appspot.com',
    iosBundleId: 'com.example.nectar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHONORJcW2h8CQERfcMYC9fvZErggJQgo',
    appId: '1:30693532203:ios:5018e26d94388fbc43006e',
    messagingSenderId: '30693532203',
    projectId: 'nectar-bbe2b',
    storageBucket: 'nectar-bbe2b.appspot.com',
    iosBundleId: 'com.example.nectar.RunnerTests',
  );
}
